### ISSUE TITLE
Theme unloads after clicking editor's vertical resize bar

### ISSUE THREAD

**Issue by Saldef** [standardnotes/web#952] opened 2022-03-25 08:32 UTC
Here is another weird, interesting and easily reproducible bug, that I also discovered accidently:

I am still having this closed [issue](https://github.com/standardnotes/web/issues/866), but I decided to just live with it, Nonethless, when I click on the editor's (any editor) vertical resize bar (below image), the chosen theme (Autobiography) will unload, and I will be defaulted to a previous custom theme that I have been using before (Muted Dark).  I have reproduced this bug on two Windows machines. 

**OS:** Windows 10
**Standard Notes Version :** 3.13.0

<img src="https://user-images.githubusercontent.com/22526505/160083485-c3aa9cdf-d229-4ca1-9422-ca96acd1ddb5.jpg" width="300" />

**Comment by moughxyz** [comment] 2022-03-25 12:13
Good catch, can reproduce 👍

**Comment by moughxyz** [comment] 2022-03-25 12:44
Hmm so about the passcode lock issue, it seems what's happening is that after you unlock the app, it's reading your Preferences > Appearance > "Use system color scheme" setting.

So it disregards whatever theme you may have manually chosen before.

Will have to think about how to solve that one since technically, it's behaving as expected, but feels like it's not 🤔

**Comment by moughxyz** [comment] 2022-03-25 13:14
The original issue in this ticket will be fixed in upcoming 3.14.0 release.

**Closed by moughxyz** 2022-03-25 13:14 UTC
